# Generated by Django 5.2.4 on 2025-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_images/"
            ),
        ),
    ]
